name: Deploy Production

on:
  pull_request:
    types:
      - closed
    branches:
      - main

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  deploy-backend:
    name: Deploy Backend (Production)
    if: github.event.pull_request.merged == true && github.event.pull_request.head.ref == 'staging'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
      
      - name: Deploy Backend to Fly
        working-directory: ./brsense-backend
        # Usa o fly.toml padrão (que é o seu de produção)
        run: flyctl deploy -c fly.toml 

  deploy-frontend:
    name: Deploy Frontend (Production)
    if: github.event.pull_request.merged == true && github.event.pull_request.head.ref == 'staging'
    runs-on: ubuntu-latest
    needs: deploy-backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
      
      - name: Deploy Frontend to Fly
        working-directory: ./brsense-frontend
        # Usa o fly.toml padrão e injeta as variáveis PROD
        run: |
          flyctl deploy -c fly.toml \
            --build-arg VITE_API_URL=${{ vars.PROD_VITE_API_URL }} \
            --build-arg VITE_KEYCLOAK_REALM=${{ vars.PROD_VITE_KEYCLOAK_REALM }} \
            --build-arg VITE_KEYCLOAK_URL=${{ vars.VITE_KEYCLOAK_URL }}