name: Deploy Staging

on:
  push:
    branches:
      - staging

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  deploy-backend:
    name: Deploy Backend (Staging)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
      
      - name: Deploy Backend to Fly
        working-directory: ./brsense-backend
        run: flyctl deploy -c fly.dev.toml # ou o nome do seu arquivo toml de staging do backend

  deploy-frontend:
    name: Deploy Frontend (Staging)
    runs-on: ubuntu-latest
    needs: deploy-backend # Garante que o frontend só faça deploy se o backend der certo (opcional)
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
      
      - name: Deploy Frontend to Fly
        working-directory: ./brsense-frontend
        # Aqui injetamos as variáveis de build diretamente no comando do Fly
        run: |
          flyctl deploy -c fly.staging.toml \
            --build-arg VITE_API_URL=${{ vars.STAGING_VITE_API_URL }} \
            --build-arg VITE_KEYCLOAK_REALM=${{ vars.STAGING_VITE_KEYCLOAK_REALM }} \
            --build-arg VITE_KEYCLOAK_URL=${{ vars.STAGING_VITE_KEYCLOAK_URL }}